# providers.tf — AWS provider for this service's thin Terraform.
#
# Region is eu-west-2 (London), matching the shared platform. No us-east-1
# alias is needed: the frontend is hosted on AWS Amplify, which manages its own
# TLS certificate. (The superseded S3 + CloudFront design needed a us-east-1
# ACM cert; Amplify does not.)
#
# The S3 remote-state backend lives in backend.tf, which is generated by
# scripts/bootstrap-state.sh — do NOT add a `backend` block here.

terraform {
  required_version = ">= 1.6.0"

  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "~> 6.0"
    }
  }
}

provider "aws" {
  region = var.aws_region

  default_tags {
    tags = {
      Service     = var.service_name
      Environment = var.environment
      ManagedBy   = "terraform"
    }
  }
}
