#!/usr/bin/env bash
# Usage: SERVICE_NAME=myapp [AWS_REGION=eu-west-2] [--dry-run] ./scripts/bootstrap-state.sh
#
# Creates the S3 bucket and DynamoDB table used as Terraform remote state,
# then writes the configured backend block into terraform/backend.tf.
# Safe to run multiple times — skips resources that already exist.

set -euo pipefail

SERVICE_NAME="${SERVICE_NAME:?SERVICE_NAME is required}"
AWS_REGION="${AWS_REGION:-eu-west-2}"
BUCKET="${SERVICE_NAME}-terraform-state"
DRY_RUN=false

for arg in "$@"; do
  [[ "$arg" == "--dry-run" ]] && DRY_RUN=true
done

log() { echo "[bootstrap] $*"; }

if $DRY_RUN; then
  log "DRY RUN — would create:"
  log "  S3 bucket:      s3://${BUCKET} (${AWS_REGION})"
  log "  terraform/backend.tf configured with above values"
  exit 0
fi

# ── S3 bucket ────────────────────────────────────────────────────────────────
if aws s3api head-bucket --bucket "$BUCKET" --region "$AWS_REGION" 2>/dev/null; then
  log "S3 bucket ${BUCKET} already exists — skipping"
else
  log "Creating S3 bucket ${BUCKET} in ${AWS_REGION}..."
  if [[ "$AWS_REGION" == "us-east-1" ]]; then
    aws s3api create-bucket --bucket "$BUCKET" --region "$AWS_REGION"
  else
    aws s3api create-bucket \
      --bucket "$BUCKET" \
      --region "$AWS_REGION" \
      --create-bucket-configuration LocationConstraint="$AWS_REGION"
  fi
  aws s3api put-bucket-versioning \
    --bucket "$BUCKET" \
    --versioning-configuration Status=Enabled
  aws s3api put-bucket-encryption \
    --bucket "$BUCKET" \
    --server-side-encryption-configuration '{
      "Rules":[{"ApplyServerSideEncryptionByDefault":{"SSEAlgorithm":"AES256"}}]
    }'
  aws s3api put-public-access-block \
    --bucket "$BUCKET" \
    --public-access-block-configuration \
      'BlockPublicAcls=true,IgnorePublicAcls=true,BlockPublicPolicy=true,RestrictPublicBuckets=true'
  log "S3 bucket created."
fi

# ── Write backend.tf ──────────────────────────────────────────────────────────
BACKEND_FILE="$(dirname "$0")/../terraform/backend.tf"

log "Writing ${BACKEND_FILE}..."
cat > "$BACKEND_FILE" <<EOF
# Generated by scripts/bootstrap-state.sh — do not edit manually.
terraform {
  backend "s3" {
    bucket         = "${BUCKET}"
    key            = "terraform.tfstate"
    region         = "${AWS_REGION}"
    use_lockfile   = true
    encrypt        = true
  }
}
EOF

log "Done. Run: cd terraform && terraform init"
